app = "dinner_time"
primary_region = "cdg"
console_command = "bin/rails console"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[build]
    build-target = "prod-api"

[env]
    RAILS_ENV = "production"

